// Regenerates lib/game/level/ship_fit_table.dart: for every cave level, which
// ships other than its par ship pass the full validator (and why not).
// `dart run tool/gen_ship_fit.dart`. Re-run after any spec or ship edit;
// test/ship_fit_table_test.dart fails until you do.
// ignore_for_file: avoid_print
import 'dart:io';

import 'package:narrow_haul/game/level/cave/level_validator.dart';
import 'package:narrow_haul/game/level/level_def.dart';
import 'package:narrow_haul/game/level/specs/world_alien.dart';
import 'package:narrow_haul/game/level/specs/world_ice.dart';
import 'package:narrow_haul/game/level/specs/world_lava.dart';
import 'package:narrow_haul/game/level/specs/world_mine.dart';
import 'package:narrow_haul/game/level/specs/world_orbit.dart';
import 'package:narrow_haul/game/level/specs/world_redoubt.dart';
import 'package:narrow_haul/game/ship/fleet.dart';
import 'package:narrow_haul/game/ship/ship_spec.dart';

/// Every cave level with its par ship id.
List<(CaveLevelDef, String)> allCaveLevels() => [
      for (final (levels, shipId) in [
        (alienLevels, alienShipId),
        (mineLevels, mineShipId),
        (iceLevels, iceShipId),
        (lavaLevels, lavaShipId),
        (orbitLevels, orbitShipId),
        (redoubtLevels, redoubtShipId),
      ])
        for (final def in levels.whereType<CaveLevelDef>()) (def, def.shipId ?? shipId),
    ];

/// The table as it should be, from the validator.
Map<String, Map<String, ShipFit>> computeShipFitTable() => {
      for (final (def, parId) in allCaveLevels())
        if (!isParOnly(def))
          def.saveId: {
            for (final s in kShips.values)
              if (s.id != parId) s.id: classifyFitIssues(validateCaveSpec(def.spec, ship: s)),
          },
    };

String renderShipFitTable(Map<String, Map<String, ShipFit>> table) {
  final b = StringBuffer()
    ..writeln('// GENERATED by `dart run tool/gen_ship_fit.dart`. Do not edit by hand.')
    ..writeln('// Ships other than each cave level\'s par ship, and whether its validator')
    ..writeln('// passes them (`shipFitOn` in lib/game/ship/fleet.dart).')
    ..writeln("import 'package:narrow_haul/game/ship/fleet.dart';")
    ..writeln()
    ..writeln('const Map<String, Map<String, ShipFit>> kShipFitTable = {');
  for (final MapEntry(key: id, value: row) in table.entries) {
    final cells = row.entries.map((e) => "'${e.key}': ShipFit.${e.value.name}").join(', ');
    b.writeln("  '$id': {$cells},");
  }
  b.writeln('};');
  return b.toString();
}

void main() {
  final sw = Stopwatch()..start();
  final table = computeShipFitTable();
  File('lib/game/level/ship_fit_table.dart').writeAsStringSync(renderShipFitTable(table));
  for (final s in kShips.values) {
    final n = table.values.where((r) => r[s.id] == ShipFit.ok).length;
    print('${s.name.padRight(8)} flies $n extra cave levels');
  }
  print('done in ${sw.elapsed.inSeconds}s');
}
