// Authoring tool: `dart run tool/generate_expedition.dart`
// lays out the Act II Expeditions from `lib/game/level/gen/outlines.dart`,
// keeps a validated layout per outline and writes them all to
// `lib/game/level/specs/expeditions_gen.dart` (then `dart format` it).
// The generator is deterministic, so an outline that didn't change comes
// out the same; only edited outlines change.
// ignore_for_file: avoid_print
import 'dart:io';

import 'package:narrow_haul/game/level/gen/expedition_generator.dart';
import 'package:narrow_haul/game/level/gen/outlines.dart';

const _out = 'lib/game/level/specs/expeditions_gen.dart';

void main() {
  final b = StringBuffer()
    ..writeln('// GENERATED by tool/generate_expedition.dart from')
    ..writeln('// lib/game/level/gen/outlines.dart. Hand edits are lost on the next run.')
    ..writeln()
    ..writeln("import 'package:narrow_haul/game/level/cave/geom.dart';")
    ..writeln("import 'package:narrow_haul/game/level/cave/level_spec.dart';")
    ..writeln("import 'package:narrow_haul/game/level/level_def.dart';")
    ..writeln()
    ..writeln('/// Act II Expeditions laid out by the generator (docs/STORY.md §3).')
    ..writeln('final List<LevelDef> generatedExpeditions = [');
  var failed = 0;
  for (final o in kExpeditionOutlines) {
    final sw = Stopwatch()..start();
    final tally = <String, int>{};
    final g = generateExpedition(o, onAttempt: (a, issues) {
      for (final i in issues) {
        final key = i.replaceAll(RegExp(r'[-0-9.,()]+'), '#').split(':').take(2).join(':');
        tally[key] = (tally[key] ?? 0) + 1;
      }
    });
    if (g == null) {
      failed++;
      print('FAIL ${o.id} ${o.name}: no layout passed (${sw.elapsedMilliseconds} ms)');
      final top = tally.entries.toList()..sort((a, b) => b.value.compareTo(a.value));
      for (final e in top.take(6)) {
        print('     ${e.value}× ${e.key}');
      }
      continue;
    }
    print('OK   ${o.id} ${o.name.padRight(20)} attempt ${g.attempt}  '
        '~${g.routeLength.round()} m  burn ${g.legFuel.map((f) => '${(f * 100).round()}%').join('/')}  '
        '3★ ${g.stars.star3Fuel} / ${g.stars.star3Time.round()} s  (${sw.elapsedMilliseconds} ms)');
    b.write(expeditionToDart(g));
  }
  b.writeln('];');
  File(_out).writeAsStringSync(b.toString());
  Process.runSync('dart', ['format', '--line-length', '100', _out]);
  print('wrote $_out${failed > 0 ? ' ($failed outline(s) failed)' : ''}');
}
