import 'package:flame_audio/flame_audio.dart';
import 'package:flutter/foundation.dart';

import 'music_service.dart';
import 'thrust_envelope.dart';

/// Thin wrapper around flame_audio. Fails silently when sound files are absent.
///
/// Files in assets/audio/ (all but attach/crash are generated by
/// `python3 tool/audio/make_sfx.py`):
///   thrust_loop.wav – engine loop, muted between burns (see [ThrustEnvelope])
///   attach.mp3      – rope attachment snap
///   crash.mp3       – hull breach / wall hit
///   land.wav        – successful landing
///   shield_hit.wav  – hull shield meeting rock (scrape / touchdown)
///   star.wav        – star(s) earned jingle
///   shot.wav        – nose cannon shot (pooled for rapid fire)
///   boom.wav        – turret / reactor explosion
///   pickup.wav      – fuel canister collected
///   enemy_shot.wav  – turret firing (pooled)
///   alarm.wav       – reactor meltdown countdown (1 s loop)
///   ui_tap.wav      – menu buttons (pooled)
///   ui_*.wav        – space UI kit sounds, see [UiSound]
///   countdown.wav / countdown_go.wav – 3·2·1 / GO before auto-launch
///   start_level.m4a – level-start sting (Space Music Pack, Goose Ninja)
/// Music tracks (music_*.m4a) are played by [MusicService].
class AudioService {
  static final _files = [
    'thrust_loop.wav',
    'attach.mp3',
    'crash.mp3',
    'land.wav',
    'shield_hit.wav',
    'star.wav',
    'shot.wav',
    'boom.wav',
    'pickup.wav',
    'enemy_shot.wav',
    'alarm.wav',
    'start_level.m4a',
    'countdown.wav',
    'countdown_go.wav',
    for (final s in UiSound.values) s.file,
  ];

  /// Respects the iOS ring/silent switch (ambient) and never interrupts the
  /// player's own music on either platform.
  static final AudioContext _context = AudioContext(
    iOS: AudioContextIOS(category: AVAudioSessionCategory.ambient),
    android: const AudioContextAndroid(
      contentType: AndroidContentType.sonification,
      usageType: AndroidUsageType.game,
      audioFocus: AndroidAudioFocus.none,
    ),
  );

  static bool _ready = false;
  static bool _enabled = true;
  static AudioPlayer? _thrustPlayer;
  static bool _thrustStarting = false;
  static bool _engineRunning = false;
  static final ThrustEnvelope _envelope = ThrustEnvelope();
  static AudioPlayer? _alarmPlayer;

  /// Files that loaded; a missing or broken one is skipped on its own.
  static final Set<String> _loaded = {};

  /// Preloaded players per one-shot sound (size = how many may overlap).
  /// Pooled players recycle on completion, unlike `FlameAudio.play`'s
  /// low-latency players, which Android never reports as complete.
  static final _poolSizes = {
    'shot.wav': 4,
    'enemy_shot.wav': 4,
    'boom.wav': 3,
    'pickup.wav': 2,
    'attach.mp3': 1,
    'crash.mp3': 1,
    'land.wav': 1,
    'shield_hit.wav': 2,
    'star.wav': 1,
    'start_level.m4a': 1,
    'countdown.wav': 1,
    'countdown_go.wav': 1,
    for (final s in UiSound.values) s.file: s.poolSize,
  };
  static final Map<String, AudioPool> _pools = {};

  @visibleForTesting
  static List<String> get files => _files;

  @visibleForTesting
  static Map<String, int> get poolSizes => _poolSizes;
  static bool _alarmWanted = false;
  static bool _alarmStarting = false;

  static bool get isReady => _ready;

  /// Shared with [MusicService].
  static AudioContext get context => _context;

  static void setEnabled(bool enabled) {
    _enabled = enabled;
    if (!enabled) {
      stopEngine();
      setAlarm(false);
    }
  }

  static void _log(String message, [Object? error]) {
    if (!kDebugMode) return;
    debugPrint('AudioService: $message${error != null ? " ($error)" : ""}');
  }

  static void _quietly(Future<void> f, String what) {
    f.then<void>(
      (_) {},
      onError: (Object e, StackTrace _) => _log('failed to $what', e),
    );
  }

  static Future<void> init() async {
    _ready = false;
    stopEngine();
    try {
      await AudioPlayer.global.setAudioContext(_context);
    } catch (e) {
      _log('audio context not applied', e);
    }
    _loaded.clear();
    for (final file in _files) {
      try {
        await FlameAudio.audioCache.load(file);
        _loaded.add(file);
      } catch (e) {
        _log('$file failed to load, skipped', e);
      }
    }
    if (_loaded.contains('thrust_loop.wav')) await _prewarmThrustLoop();
    for (final MapEntry(key: file, value: size) in _poolSizes.entries) {
      if (!_loaded.contains(file)) continue;
      final pool = await _pool(file, size);
      if (pool != null) _pools[file] = pool;
    }
    _ready = _loaded.isNotEmpty;
    _log('initialized ${_loaded.length}/${_files.length} sounds');
  }

  /// Preloaded players for a one-shot; null falls back to one-off players.
  static Future<AudioPool?> _pool(String file, int maxPlayers) async {
    try {
      return await FlameAudio.createPool(
        file,
        maxPlayers: maxPlayers,
        audioContext: _context,
      );
    } catch (e) {
      _log('$file pool failed, using one-off players', e);
      return null;
    }
  }

  // ── Engine ────────────────────────────────────────────────────────────────

  /// Call every frame of a flight. Keeps the loop running muted and shapes
  /// its volume, so even a one-frame tap on THRUST is heard.
  static void updateEngine({required bool thrusting, required double dt}) {
    if (!_ready || !_enabled) return;
    final player = _thrustPlayer;
    if (player == null) {
      _startThrustLoopLazily();
      return;
    }
    if (!_engineRunning) {
      _engineRunning = true;
      _envelope.reset();
      _quietly(player.setVolume(0), 'mute thrust loop');
      _quietly(player.resume(), 'resume thrust loop');
    }
    final volume = _envelope.step(thrusting, dt);
    if (volume != null) _quietly(player.setVolume(volume), 'set thrust volume');
  }

  /// Silences and pauses the engine loop (pause menu, crash, landing, menu).
  static void stopEngine() {
    _envelope.reset();
    if (!_engineRunning) return;
    _engineRunning = false;
    final player = _thrustPlayer;
    if (player == null) return;
    _quietly(player.setVolume(0), 'mute thrust loop');
    _quietly(player.pause(), 'pause thrust loop');
  }

  static Future<void> _prewarmThrustLoop() async {
    try {
      final player = await FlameAudio.loopLongAudio(
        'thrust_loop.wav',
        volume: 0,
        audioContext: _context,
      );
      await player.pause();
      _thrustPlayer = player;
      _log('thrust loop prewarmed');
    } catch (e) {
      _thrustPlayer = null;
      _log('thrust prewarm failed, falling back to lazy start', e);
    }
  }

  static void _startThrustLoopLazily() {
    if (_thrustStarting) return;
    _thrustStarting = true;
    FlameAudio.loopLongAudio('thrust_loop.wav', volume: 0, audioContext: _context)
        .then((p) {
      _thrustPlayer = p;
      _thrustStarting = false;
      // Running muted; the next updateEngine resumes it if still flying.
      _quietly(p.pause(), 'pause thrust loop');
    }).catchError((Object e) {
      _thrustStarting = false;
      _log('failed to start thrust loop', e);
    });
  }

  /// Releases the players (app shutdown / test teardown).
  static Future<void> dispose() async {
    final players = [_thrustPlayer, _alarmPlayer];
    final pools = [..._pools.values];
    _pools.clear();
    _loaded.clear();
    _thrustPlayer = _alarmPlayer = null;
    _engineRunning = false;
    _alarmWanted = false;
    _ready = false;
    for (final p in players) {
      await p?.dispose();
    }
    for (final p in pools) {
      await p.dispose();
    }
    await MusicService.dispose();
  }

  // ── Meltdown alarm ────────────────────────────────────────────────────────

  /// Idempotent: call every frame with whether the alarm should sound.
  static void setAlarm(bool on) {
    if (on && (!_ready || !_enabled || !_loaded.contains('alarm.wav'))) {
      on = false;
    }
    if (on == _alarmWanted) return;
    _alarmWanted = on;
    final player = _alarmPlayer;
    if (on) {
      if (player != null) {
        _quietly(player.resume(), 'resume alarm');
      } else if (!_alarmStarting) {
        _alarmStarting = true;
        FlameAudio.loop('alarm.wav', volume: 0.45, audioContext: _context)
            .then((p) {
          _alarmPlayer = p;
          _alarmStarting = false;
          if (!_alarmWanted) _quietly(p.pause(), 'pause alarm');
        }).catchError((Object e) {
          _alarmStarting = false;
          _log('failed to start alarm', e);
        });
      }
    } else if (player != null) {
      _quietly(player.pause(), 'pause alarm');
    }
  }

  // ── One-shots ─────────────────────────────────────────────────────────────

  static void _play(String file, double volume) {
    if (!_ready || !_enabled || !_loaded.contains(file)) return;
    final pool = _pools[file];
    if (pool != null) {
      pool.start(volume: volume).then<void>(
        (_) {},
        onError: (Object e, StackTrace _) => _log('failed to play $file', e),
      );
      return;
    }
    // No pool: a one-off player, released after a while (completion events
    // aren't reliable for low-latency players).
    FlameAudio.play(file, volume: volume, audioContext: _context).then<void>(
      (p) => Future<void>.delayed(const Duration(seconds: 8), () {
        _quietly(p.dispose(), 'dispose $file');
      }),
      onError: (Object e, StackTrace _) => _log('failed to play $file', e),
    );
  }

  static void playAttach() => _play('attach.mp3', 0.8);

  static void playPickup() => _play('pickup.wav', 0.7);

  static void playCrash() {
    stopEngine();
    _play('crash.mp3', 0.9);
  }

  static void playShot() => _play('shot.wav', 0.5);

  static void playEnemyShot() => _play('enemy_shot.wav', 0.55);

  static void playTap() => playUi(UiSound.tap);

  /// Space UI kit sound (buttons, panels, switches).
  static void playUi(UiSound sound) => _play(sound.file, sound.volume);

  /// Explosion that isn't the player's crash (keeps the engine loop going).
  static void playBoom() => _play('boom.wav', 0.7);

  static void playLand() {
    stopEngine();
    _play('land.wav', 0.9);
  }

  /// Hull shield meeting rock: a scrape, or softer for a touchdown (keeps
  /// the engine loop going).
  static void playScrape({bool touchdown = false}) =>
      _play('shield_hit.wav', touchdown ? 0.4 : 0.6);

  static void playStar() => _play('star.wav', 0.8);

  /// Level-start sting (Goose Ninja, Space Music Pack).
  static void playStartLevel() => _play('start_level.m4a', 0.8);

  /// Start countdown: a beep for 3, 2, 1 and a higher one for GO.
  static void playCountdown({required bool go}) =>
      _play(go ? 'countdown_go.wav' : 'countdown.wav', 0.5);
}

/// Menu sounds of the space UI kit (`lib/ui/space_ui.dart`), quiet enough to
/// sit under the menu music.
enum UiSound {
  /// Generic button blip.
  tap('ui_tap.wav', 0.35, 2),

  /// LAUNCH / Retry / Next: power-up whoosh.
  launch('ui_launch.wav', 0.4, 1),

  /// Tiles and secondary buttons.
  select('ui_select.wav', 0.3, 2),

  /// Back buttons and the back key.
  back('ui_back.wav', 0.3, 2),

  /// A panel or popover slides in.
  open('ui_open.wav', 0.25, 1),

  /// A panel or popover slides out.
  close('ui_close.wav', 0.25, 1),
  toggleOn('ui_toggle_on.wav', 0.35, 1),
  toggleOff('ui_toggle_off.wav', 0.35, 1),

  /// Locked or can't afford.
  denied('ui_denied.wav', 0.3, 1);

  const UiSound(this.file, this.volume, this.poolSize);
  final String file;
  final double volume;
  final int poolSize;
}
